(() => {
  if (!globalThis.chrome?.runtime || !document.getElementById('webscadaAlarms')) return;
  const $ = id => document.getElementById(id); let catalog = [], editingId = '';
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const send = (type, payload) => chrome.runtime.sendMessage({ type, payload });
  const csv = (name, rows) => { const keys = Object.keys(rows[0] || {}); if (!keys.length) return; const text = '\ufeff' + [keys.join(';'), ...rows.map(row => keys.map(key => `"${String(row[key] ?? '').replace(/"/g, '""')}"`).join(';'))].join('\r\n'); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' })), download: name }); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); };
  const statusLabel = status => status?.lastError ? 'HATA' : status?.enabled ? 'AKTİF' : 'KAPALI';
  function scopeLabel(rule) { return ({ selected: 'Seçili varlık', multi: 'Seçili varlıklar', 'all-hats': 'Tüm Hatlar', 'all-trafos': 'Tüm Trafolar', filter: 'Filtreli grup' })[rule.scopeType] || rule.scopeType; }
  async function loadCatalog() { const network = await WebSCADATopology.loadTopology(); const hierarchy = WebSCADAYtbsHierarchy.create(network); catalog = WebSCADAAlarmCatalog.build(network, hierarchy); await send('ALARM_SYNC_CATALOG', { catalog }); const ytm = [...new Set(catalog.flatMap(x => x.ytm))].sort((a,b) => a.localeCompare(b, 'tr')); const bm = [...new Set(catalog.flatMap(x => x.bm))].sort((a,b) => a.localeCompare(b, 'tr')); $('alarmYtm').insertAdjacentHTML('beforeend', ytm.map(x => `<option>${esc(x)}</option>`).join('')); $('alarmBm').insertAdjacentHTML('beforeend', bm.map(x => `<option>${esc(x)}</option>`).join('')); fillEntities(); }
  function fillEntities() { const scope = $('alarmScope').value, type = scope === 'all-trafos' ? 'trafo' : 'hat'; const selected = WebSCADASelection.get(); const values = catalog.filter(x => x.entityType === type); $('alarmEntity').multiple = scope === 'multi'; $('alarmEntity').size = scope === 'multi' ? 6 : 1; $('alarmEntity').innerHTML = `${scope === 'multi' ? '' : '<option value="">Varlık seçin</option>'}${values.map(x => `<option value="${esc(x.entityId)}" ${selected && String(selected.id) === x.entityId ? 'selected' : ''}>${esc(x.entityName)} · ${esc(x.kv)} kV</option>`).join('')}`; }
  function render(data) { const { settings, rules, runtime, events, cycles, status } = data; $('alarmBackgroundEnabled').checked = Boolean(settings.backgroundMonitoringEnabled); $('alarmNavCount').textContent = status.activeAlarmCount ? `(${status.activeAlarmCount})` : ''; $('alarmStatusGrid').innerHTML = [['Arka plan', statusLabel(status)], ['Son kontrol', status.lastCompletedAt ? new Date(status.lastCompletedAt).toLocaleTimeString('tr-TR') : '—'], ['İzlenen', status.monitoredEntityCount || 0], ['Aktif alarm', status.activeAlarmCount || 0], ['SCADA', status.lastAuthMode || '—']].map(([k,v]) => `<div><small>${k}</small><b>${esc(v)}</b></div>`).join('');
    $('alarmRules').innerHTML = rules.length ? `<div class="alarm-rule-list">${rules.map(rule => `<div class="alarm-row"><span><b>${esc(rule.name)}</b><br><small>${esc(scopeLabel(rule))} · ≥%${esc(rule.thresholdPct)} · ${rule.capacitySeason === 'summer' ? 'Yaz' : 'Kış'}</small></span><span><button data-edit="${esc(rule.id)}">Düzenle</button> <button data-delete="${esc(rule.id)}">Sil</button></span></div>`).join('')}</div>` : '<p class="workspace-note">Henüz kural yok.</p>';
    const active = Object.entries(runtime).filter(([, entry]) => entry.state === 'ACTIVE' || entry.state === 'ACTIVE_DATA_UNAVAILABLE'); $('alarmActive').innerHTML = active.length ? active.map(([key, entry]) => `<div class="alarm-row active"><span><b>${esc(entry.entityName)}</b><br><small>%${Number(entry.loadingPct).toFixed(1)} · Limit %${entry.thresholdPct} · ${entry.state === 'ACTIVE_DATA_UNAVAILABLE' ? 'Güncel veri yok' : 'AKTİF'}</small></span><span><button data-map="${esc(entry.entityId)}">Harita</button> <button data-ack="${esc(key)}">ACK</button> <button data-snooze="${esc(key)}">15 dk</button></span></div>`).join('') : '<p class="workspace-note">Aktif alarm yok.</p>';
    $('alarmEvents').innerHTML = events.slice().reverse().slice(0, 80).map(event => `<div class="alarm-row"><span><b>${esc(event.entityName)}</b><br><small>${new Date(event.at).toLocaleString('tr-TR')} · ${esc(event.type)} · ${Number.isFinite(event.loadingPct) ? '%' + event.loadingPct.toFixed(1) : 'Veri yok'}</small></span></div>`).join('') || '<p class="workspace-note">Olay yok.</p>';
    $('alarmCycles').innerHTML = cycles.slice().reverse().map(cycle => `<div class="alarm-row"><span><b>${esc(cycle.source || '—')}</b><br><small>${cycle.completedAt ? new Date(cycle.completedAt).toLocaleTimeString('tr-TR') : '—'} · ${cycle.durationMs || 0} ms · ${cycle.measurementIdCount || 0} ölçüm · ${cycle.error || 'OK'}</small></span></div>`).join('') || '<p class="workspace-note">Yenileme yok.</p>';
    $('alarmDiagnostics').textContent = JSON.stringify({ scheduler: 'webscada-background-monitor / 1 dk', status, ruleCount: rules.length, catalogEntities: catalog.length }, null, 2);
  }
  async function refresh() { const data = await send('ALARM_GET_STATE'); if (data?.ok) render(data); return data; }
  function collect() { const scopeType = $('alarmScope').value; const ids = [...$('alarmEntity').selectedOptions].map(option => option.value).filter(Boolean); if (scopeType === 'selected' && !ids.length && WebSCADASelection.get()?.id) ids.push(String(WebSCADASelection.get().id)); return { id: editingId || undefined, name: $('alarmName').value, enabled: $('alarmRuleEnabled').checked, scopeType, entityIds: ['selected', 'multi'].includes(scopeType) ? ids : [], filters: { ytm: $('alarmYtm').value, bm: $('alarmBm').value, tm: $('alarmTm').value.trim(), kv: $('alarmKv').value, type: scopeType === 'all-trafos' ? 'trafo' : scopeType === 'all-hats' ? 'hat' : '' }, thresholdPct: Number($('alarmThreshold').value), hysteresisPct: Number($('alarmHysteresis').value), capacitySeason: $('alarmSeason').value, notificationEnabled: $('alarmNotification').checked, soundEnabled: $('alarmSound').checked, repeatMinutes: Number($('alarmRepeat').value) }; }
  function edit(rule) { editingId = rule.id; $('alarmName').value = rule.name; $('alarmScope').value = rule.scopeType; fillEntities(); $('alarmEntity').value = rule.entityIds?.[0] || ''; $('alarmThreshold').value = rule.thresholdPct; $('alarmHysteresis').value = rule.hysteresisPct; $('alarmSeason').value = rule.capacitySeason; $('alarmRepeat').value = rule.repeatMinutes; $('alarmNotification').checked = rule.notificationEnabled; $('alarmSound').checked = rule.soundEnabled; $('alarmRuleEnabled').checked = rule.enabled; }
  function bind() { $('alarmBackgroundEnabled').onchange = async () => { await send('ALARM_SET_ENABLED', { enabled: $('alarmBackgroundEnabled').checked }); refresh(); }; $('alarmScope').onchange = fillEntities; $('alarmSave').onclick = async () => { const response = await send('ALARM_SAVE_RULE', collect()); $('alarmRuleHint').textContent = response?.ok ? 'Kural kaydedildi.' : response?.error || 'Kural kaydedilemedi.'; if (response?.ok) { editingId = ''; render(response); } }; $('alarmRunNow').onclick = async () => { $('alarmRunNow').disabled = true; const result = await send('ALARM_RUN_NOW'); $('alarmRuleHint').textContent = result?.ok ? 'Kontrol tamamlandı.' : result?.error || result?.skipped || 'Kontrol yapılamadı.'; $('alarmRunNow').disabled = false; refresh(); }; $('alarmTestNotification').onclick = () => send('ALARM_TEST_NOTIFICATION'); $('alarmTestSound').onclick = () => send('ALARM_TEST_SOUND'); $('alarmEventsCsv').onclick = async () => { const x = await refresh(); csv('WebSCADA_alarm_olaylari.csv', x.events.map(e => ({ Zaman: e.at, Varlik: e.entityName, Tur: e.entityType, Olay: e.type, Yuklenme: e.loadingPct, Limit: e.thresholdPct, Kapasite: e.capacityMva, Sezon: e.capacitySeason, Durum: e.stateTo }))); }; $('alarmCyclesCsv').onclick = async () => { const x = await refresh(); csv('WebSCADA_yenilemeler.csv', x.cycles.map(c => ({ Zaman: c.completedAt, Kaynak: c.source, SureMs: c.durationMs, Varlik: c.monitoredEntityCount, Olcum: c.measurementIdCount, Satir: c.returnedRowCount, Eksik: c.missingEntityCount, Maksimum: c.maxLoadingPct, Alarm: c.activeAlarmCount, Durum: c.error || 'OK' }))); }; $('webscadaAlarms').onclick = async event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.delete && confirm('Bu alarm kuralı silinsin mi?')) { await send('ALARM_DELETE_RULE', { id: button.dataset.delete }); refresh(); } if (button.dataset.edit) { const data = await refresh(); edit(data.rules.find(r => r.id === button.dataset.edit)); } if (button.dataset.ack) { await send('ALARM_ACK', { key: button.dataset.ack }); refresh(); } if (button.dataset.snooze) { await send('ALARM_SNOOZE', { key: button.dataset.snooze, minutes: 15 }); refresh(); } if (button.dataset.map) { WebSCADASelection.select({ id: button.dataset.map, kind: 'hat' }); document.querySelector('[data-webscada-tab="map"]')?.click(); } }; chrome.storage.onChanged.addListener((_changes, area) => { if (area === 'local') refresh(); }); }
  document.addEventListener('DOMContentLoaded', async () => { try { await loadCatalog(); bind(); await refresh(); const focus = await chrome.storage.local.get('webscadaAlarmUiFocus'); if (focus.webscadaAlarmUiFocus?.tab === 'alarms') document.querySelector('[data-webscada-tab="alarms"]')?.click(); } catch (error) { $('alarmRuleHint').textContent = error.message || String(error); } });
})();
