const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const hierarchy=require('../core/ytbs-hierarchy.js'); const resolver=require('../core/entity-resolver.js'); const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','kml_layers_v2.json'),'utf8')); const h=hierarchy.create(data);
test('canonical current model has nine operational YTMs and 22 regional BMs',()=>{assert.equal(h.ytmOptions.length,9);assert.equal(h.bmOptions.length,22);assert.ok(!h.ytmOptions.includes('Milli YTM'));assert.ok(!h.bmOptions.includes('İşletme Dairesi'));});
test('multi-YTM line remains discoverable by each endpoint YTM without joined option',()=>{const line=h.hats.find(x=>x.__ytbs.ytm.length>1);assert.ok(line);assert.ok(line.__ytbs.ytm.every(y=>h.matches(line,{ytm:y})));assert.ok(!h.ytmOptions.some(y=>y.includes(',')));});
test('hierarchy resolves TM children and TM is not a workspace SCADA/query entity',()=>{const tm=h.tms.find(x=>h.children(x).hats.length&&h.children(x).trafos.length&&h.children(x).baras.length);assert.ok(tm);assert.equal(resolver.hasScadaMatch({kind:'tm',scada:{active:{ids:['x']}}}),false);assert.equal(resolver.resolveMeasurementDescriptors({kind:'tm',scada:{active:{ids:['x']}}},['P'],[]).length,0);});
test('canonical transformer classifier preserves transmission, distribution and unknown',()=>{assert.equal(hierarchy.classifyTrafo({gerilimTuru:'İletim Trafosu'}),'transmission');assert.equal(hierarchy.classifyTrafo({gerilimTuru:'Dağıtım Trafosu'}),'distribution');assert.equal(hierarchy.classifyTrafo({gerilimTuru:''}),'unknown');assert.ok(h.trafos.some(x=>x.trafoClass==='transmission'));assert.ok(h.trafos.some(x=>x.trafoClass==='distribution'));});
test('workspace layout switches map locking and workspace scrolling through explicit mode classes',()=>{const css=fs.readFileSync(path.join(__dirname,'..','app.css'),'utf8'), app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(css,/webscada-mode-workspace[\s\S]*overflow-y:auto/);assert.match(css,/webscada-mode-map[\s\S]*overflow:hidden/);assert.match(app,/webscada-mode-workspace/);});
test('query selector rejects TM and clears a selection that no longer matches its type filter',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');const normalizer=fs.readFileSync(path.join(__dirname,'..','core','query-normalizer.js'),'utf8');assert.match(app,/e\.kind!=='tm'/);assert.match(app,/if\(app\.selected&&!list\.some\(e=>e===app\.selected\)\)clearSelection\(\)/);assert.match(normalizer,/terminalKey/);});
test('data detail resolves the clicked entity and SCADA matched filters exclude TM rows',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');const detail=app.match(/function detail\(e\)\{[\s\S]*?function csv/)[0];assert.match(detail,/resolveMeasurementDescriptors\(e,metrics,app\.entities\)/);assert.doesNotMatch(detail,/const ds=descriptors\(\)/);assert.match(app,/e\.kind!=='tm'&&\(scada==='matched'\)/);assert.ok(!/e\.kind==='tm\?scada==='unmatched'/.test(app));});
