(function (root, factory) {
  const api = factory(); if (typeof module === 'object' && module.exports) module.exports = api; root.WebSCADAAlarmCatalog = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const numeric = (v) => Number.isFinite(Number(v)) && Number(v) > 0 ? Number(v) : null;
  const pick = (...values) => values.map(numeric).find(Boolean) || null;
  function typeOf(entity, supplied) { if (supplied === 'bara' || entity.kind === 'bara') return 'bara'; return supplied === 'trafo' || entity.kind === 'trafo' ? 'trafo' : 'hat'; }
  function tmName(entity) { return entity.kind === 'hat' ? `${entity.startTm || ''} ↔ ${entity.endTm || ''}` : String(entity.tmName || entity.trafoMerkezi || entity.tm || ''); }
  function descriptors(entity, metric) { const field = metric === 'P' ? 'active' : 'reactive'; return (entity?.scada?.[field]?.rows || []).map((row) => ({ id: String(row.measurementId || ''), metric, terminalKey: row.terminalSide || row.sourceTmName || row.formulaStationCode || '', terminalSide: row.terminalSide || '', candidateSlot: row.candidateSlot || row.role || '', sourceSide: row.sourceSide || '', targetSide: row.targetSide || '', formulaSign: Number.isFinite(Number(row.formulaSign ?? row.polarizationSign)) ? Number(row.formulaSign ?? row.polarizationSign) : 1 })).filter((row) => row.id); }
  function build(network, hierarchy) {
    const result = []; const add = (entity, suppliedType) => { const active = descriptors(entity, 'P'); const reactive = descriptors(entity, 'Q'); const kind = typeOf(entity, suppliedType); const winterCapacityMva = kind === 'hat' ? pick(entity.winterCapacityMva, entity.summerCapacityMva) : pick(entity.ofafMva, entity.onafMva, entity.onanMva, entity.bazGucuMva); const summerCapacityMva = kind === 'hat' ? pick(entity.summerCapacityMva, entity.winterCapacityMva) : winterCapacityMva; const membership = entity.__ytbs || hierarchy?.memberships?.(entity) || {}; const entityName = entity.displayName || entity.name || String(entity.id); const tm = tmName(entity); const kv = String(entity.kvBucket || entity.kv || entity.primaryKv || entity.gerilimKv || ''); const trafoClass = hierarchy?.classifyTrafo?.(entity) || entity.trafoClass || (/iletim|transmission/i.test(String(entity.gerilimTuru || entity.trafoType || entity.type || '')) ? 'transmission' : 'distribution'); const trafoType = trafoClass === 'transmission' ? 'İletim' : 'Dağıtım'; const entityDisplayName = kind === 'trafo' ? `${tm || '-'} >> ${kv || '-'} kV >> ${trafoType} >> ${entityName}` : entityName; result.push({ entityId: String(entity.id), entityName, entityDisplayName, entityType: kind, tmName: tm, tm, kv, trafoType, ytm: membership.ytm || entity.ytmNames || [], bm: membership.bm || [], winterCapacityMva, summerCapacityMva, activeDescriptors: active, reactiveDescriptors: reactive }); };
    (network?.hatLines || []).forEach(entity => add(entity, 'hat')); (network?.trafos || []).forEach(entity => add(entity, 'trafo')); (network?.baraNodes || []).forEach(entity => add(entity, 'bara')); return result;
  }
  function matchesRuleFilters(entity, filters = {}) { const exact = (values, wanted) => !wanted || (Array.isArray(values) ? values : []).map(String).includes(String(wanted)); return (!filters.type || entity.entityType === filters.type) && exact(entity.ytm, filters.ytm) && exact(entity.bm, filters.bm) && (!filters.tm || String(entity.tm) === String(filters.tm)) && (!filters.kv || entity.kv === String(filters.kv)); }
  function resolve(rule, catalog) { const all = Array.isArray(catalog) ? catalog : []; const scope = rule?.scopeType || 'selected'; const filters = rule?.filters || {}; const selectedType = scope === 'all-hats' ? 'hat' : scope === 'all-trafos' ? 'trafo' : scope === 'filter' ? (filters.type === 'trafo' ? 'trafo' : 'hat') : filters.type || ''; const wantedType = selectedType || (scope.includes('trafo') ? 'trafo' : scope.includes('hat') ? 'hat' : ''); const ids = new Set((rule?.entityIds || []).map(String)); return all.filter(entity => (!wantedType || entity.entityType === wantedType) && (scope === 'filter' || scope.startsWith('all-') ? matchesRuleFilters(entity, { ...filters, type: wantedType || filters.type }) : ids.has(entity.entityId) && matchesRuleFilters(entity, filters))); }
  function ids(entries) { return [...new Set((entries || []).flatMap(x => [...x.activeDescriptors, ...x.reactiveDescriptors]).map(x => x.id))]; }
  return { build, resolve, ids, matchesRuleFilters };
}));
