const WebSCADAAlarmMonitor = (() => {
  const KEYS = { settings: 'webscadaAlarmSettings', rules: 'webscadaAlarmRules', runtime: 'webscadaAlarmRuntime', checks: 'webscadaAlarmRuleChecks', events: 'webscadaAlarmEvents', cycles: 'webscadaMonitorCycles', samples: 'webscadaAlarmSamples', catalog: 'webscadaAlarmCatalog', catalogVersion: 'webscadaAlarmCatalogVersion', status: 'webscadaBackgroundMonitorStatus', lease: 'alarmMonitorLease', snapshot: 'scadaDashboardSnapshot', notificationStatus: 'webscadaNotificationStatus' };
  const get = async (...keys) => chrome.storage.local.get(keys); const set = value => chrome.storage.local.set(value); const iso = () => new Date().toISOString();
  const rows = result => Array.isArray(result?.data?.result) ? result.data.result.flatMap(item => Array.isArray(item?.data) ? item.data : []) : [];
  async function catalog() { const current = await get(KEYS.catalog, KEYS.catalogVersion); const version = chrome.runtime.getManifest().version; if (Array.isArray(current[KEYS.catalog]) && current[KEYS.catalogVersion] === version) return current[KEYS.catalog]; const network = await fetch(chrome.runtime.getURL('data/kml_layers_v2.json')).then(response => response.json()); const hierarchy = self.WebSCADAYtbsHierarchy?.create?.(network); const next = WebSCADAAlarmCatalog.build(network, hierarchy); await set({ [KEYS.catalog]: next, [KEYS.catalogVersion]: version }); return next; }
  function plan(rules, items) { const entities = [...new Map(rules.flatMap(rule => WebSCADAAlarmCatalog.resolve(rule, items).map(entity => [entity.entityId, entity]))).values()]; return { entities, measurementIds: WebSCADAAlarmCatalog.ids(entities) }; }
  function snapshotRows(snapshot, ids) { const at = Number(snapshot?.at || snapshot?.createdAt || 0); const data = snapshot?.rows || snapshot?.data || (snapshot?.measurementRows || []).map(([key, row]) => ({ ...row, sinsid: String(key).split('|')[0], elementName: String(key).split('|')[1] || row?.elementName })); if (Date.now() - at > 45000 || !Array.isArray(data)) return { rows: [], reusedIds: [], missingIds: ids.slice() }; const byId = new Set(data.map(row => String(row.sinsid ?? row.measurementId ?? '')).filter(Boolean)); const reusedIds = ids.filter(id => byId.has(String(id))); return { rows: data.filter(row => reusedIds.includes(String(row.sinsid ?? row.measurementId ?? ''))), reusedIds, missingIds: ids.filter(id => !byId.has(String(id))) }; }
  function dueRules(rules, checks, options, now) { const forced = new Set((options?.forceRuleIds || []).map(String)); return rules.filter(rule => forced.has(String(rule.id)) || now - Number(checks?.[rule.id] || 0) >= Number(rule.checkIntervalMinutes || 1) * 60000); }
  function reconcileAlarmRuntime(rules, runtime, checks, items) { const activeRules = (rules || []).map(WebSCADAAlarmModel.rule).filter(rule => rule.enabled); const allowed = new Map(activeRules.map(rule => [String(rule.id), new Set(WebSCADAAlarmCatalog.resolve(rule, items).map(entity => String(entity.entityId)))])); const nextRuntime = {}; Object.entries(runtime || {}).forEach(([key, entry]) => { const ruleId = String(entry?.ruleId || key.split(':')[0]); const entityId = String(entry?.entityId || key.slice(ruleId.length + 1)); if (allowed.get(ruleId)?.has(entityId)) nextRuntime[key] = entry; }); const nextChecks = {}; Object.entries(checks || {}).forEach(([ruleId, value]) => { if (allowed.has(String(ruleId))) nextChecks[ruleId] = value; }); return { runtime: nextRuntime, checks: nextChecks, activeRules, removedRuntimeCount: Object.keys(runtime || {}).length - Object.keys(nextRuntime).length }; }
  const activeCount = runtime => Object.values(runtime || {}).filter(entry => entry.state === 'ACTIVE' || entry.state === 'ACTIVE_DATA_UNAVAILABLE').length;
  async function reconcileStored(rules, runtime, checks, items) { const next = reconcileAlarmRuntime(rules, runtime, checks, items); await set({ [KEYS.runtime]: next.runtime, [KEYS.checks]: next.checks }); return next; }
  async function acquire() { const current = await get(KEYS.lease); const lease = current[KEYS.lease]; if (lease?.running && Number(lease.expiresAt) > Date.now()) return false; await set({ [KEYS.lease]: { running: true, startedAt: Date.now(), expiresAt: Date.now() + 120000 } }); return true; }
  async function release() { await set({ [KEYS.lease]: { running: false, startedAt: 0, expiresAt: 0 } }); }
  async function recordWake(data = {}) { const prior = await get(KEYS.status); await set({ [KEYS.status]: { ...(prior[KEYS.status] || {}), lastWakeAt: iso(), schedulerExists: data.schedulerExists ?? true, schedulerPeriodMinutes: data.schedulerPeriodMinutes ?? 1, schedulerScheduledTime: data.schedulerScheduledTime || prior[KEYS.status]?.schedulerScheduledTime || null } }); }
  async function finalizeCycleStatus(prior, started, trigger, fields = {}) { const completedAt = iso(); const status = { ...(prior || {}), enabled: fields.enabled ?? Boolean(prior?.enabled), running: false, lastWakeAt: prior?.lastWakeAt || completedAt, lastStartedAt: new Date(started).toISOString(), lastCompletedAt: completedAt, lastTrigger: trigger, lastSkippedReason: fields.skipped || '', lastDurationMs: Date.now() - started, nextExpectedAt: new Date(Date.now() + 60000).toISOString(), lastError: fields.error || '', ...fields }; delete status.skipped; await set({ [KEYS.status]: status }); return status; }
  async function broadcast(events) { if (!events.length || !chrome.tabs?.query) return; const tabs = await chrome.tabs.query({ url: chrome.runtime.getURL('app.html') }); await Promise.all(tabs.map(tab => chrome.tabs.sendMessage(tab.id, { type: 'ALARM_EVENT', events }).catch(() => {}))); }
  function eventFor(type, rule, entity, prior, next, outcome, key) { return { id: `${Date.now()}-${key}-${type}`, at: iso(), type, severity: rule.severity, ruleId: rule.id, entityId: entity.entityId, entityName: entity.entityName, displayLabel: entity.entityDisplayName || entity.entityName, entityType: entity.entityType, tm: entity.tmName || entity.tm || '', kv: entity.kv || '', trafoType: entity.trafoType || '', stateFrom: prior.state || 'NORMAL', stateTo: next.state, loadingPct: outcome.loadingPct, thresholdPct: rule.thresholdPct, capacityMva: outcome.capacityMva, capacitySeason: rule.capacitySeason, valueTimestamp: outcome.valueTimestamp, notificationSent: false, soundPlayed: false, acknowledged: Boolean(next.acknowledgedAt) }; }
  async function run(trigger = 'alarm-background', options = {}) {
    if (!await acquire()) { const prior = await get(KEYS.status); await set({ [KEYS.status]: { ...(prior[KEYS.status] || {}), lastWakeAt: iso(), lastTrigger: trigger, lastSkippedReason: 'overlap' } }); return { ok: false, skipped: 'overlap' }; }
    const started = Date.now();
    try {
      const saved = await get(KEYS.settings, KEYS.rules, KEYS.runtime, KEYS.checks, KEYS.events, KEYS.cycles, KEYS.samples, KEYS.snapshot, KEYS.status, KEYS.notificationStatus); const settings = saved[KEYS.settings] || { backgroundMonitoringEnabled: false }; const rules = saved[KEYS.rules] || []; const all = rules.length ? await catalog() : [];
      const reconciled = reconcileAlarmRuntime(rules, saved[KEYS.runtime], saved[KEYS.checks], all); if (reconciled.removedRuntimeCount || Object.keys(saved[KEYS.checks] || {}).length !== Object.keys(reconciled.checks).length) await set({ [KEYS.runtime]: reconciled.runtime, [KEYS.checks]: reconciled.checks }); const enabledRules = reconciled.activeRules;
      const startStatus = { ...(saved[KEYS.status] || {}), enabled: Boolean(settings.backgroundMonitoringEnabled), running: true, lastWakeAt: iso(), lastStartedAt: new Date(started).toISOString(), lastTrigger: trigger, lastSkippedReason: '', lastError: '', activeAlarmCount: activeCount(reconciled.runtime) }; await set({ [KEYS.status]: startStatus });
      if (!settings.backgroundMonitoringEnabled || !enabledRules.length) return { ok: true, skipped: 'disabled', status: await finalizeCycleStatus(startStatus, started, trigger, { enabled: Boolean(settings.backgroundMonitoringEnabled), skipped: 'disabled', activeAlarmCount: activeCount(reconciled.runtime) }) };
      const prepared = dueRules(enabledRules, reconciled.checks, options, started); if (!prepared.length) return { ok: true, skipped: 'not-due', status: await finalizeCycleStatus(startStatus, started, trigger, { enabled: true, skipped: 'not-due', activeAlarmCount: activeCount(reconciled.runtime) }) };
      const queryPlan = plan(prepared, all); if (!queryPlan.measurementIds.length) return { ok: true, skipped: 'no-measurements', status: await finalizeCycleStatus(startStatus, started, trigger, { enabled: true, skipped: 'no-measurements', activeAlarmCount: activeCount(reconciled.runtime) }) };
      const snapshot = snapshotRows(saved[KEYS.snapshot], queryPlan.measurementIds); let values = snapshot.rows.slice(), source = snapshot.missingIds.length ? (snapshot.reusedIds.length ? 'mixed' : 'network') : 'map-snapshot', result = null;
      if (snapshot.missingIds.length) { const payload = { measurementIds: snapshot.missingIds, elementNames: ['P', 'Q'] }; result = await WebSCADARequestCoordinator.run({ key: WebSCADARequestCoordinator.requestKey('ALARM_NETWORK_QUERY', payload), priority: 1, label: 'Alarm arka plan kontrolü' }, () => WebSCADAQuery.executeLiveScada(payload)); if (!result?.ok) throw Object.assign(new Error(result?.error || 'SCADA sorgusu başarısız.'), { authMode: result?.authMode || 'none' }); values = values.concat(rows(result)); }
      const runtime = { ...reconciled.runtime }; let events = saved[KEYS.events] || []; let samples = saved[KEYS.samples] || {}; let notifications = 0, newCount = 0, cleared = 0, max = null, soundSeverity = '', lastNotificationResult = '', lastSoundResult = ''; const emittedEvents = [], soundEvents = [] ; const globalSettings = await WebSCADASettings.load();
      for (const rule of prepared) for (const entity of WebSCADAAlarmCatalog.resolve(rule, all)) {
        const key = `${rule.id}:${entity.entityId}`; const outcome = WebSCADAAlarmEvaluator.evaluate(entity, values, rule.capacitySeason, Date.now()); const prior = runtime[key] || {}; const next = WebSCADAAlarmModel.nextState(prior, { ...rule, valueTimestamp: outcome.valueTimestamp }, outcome.loadingPct); Object.assign(next, { entityId: entity.entityId, entityName: entity.entityName, entityDisplayName: entity.entityDisplayName || entity.entityName, entityType: entity.entityType, tm: entity.tmName || entity.tm || '', kv: entity.kv || '', trafoType: entity.trafoType || '', ruleId: rule.id, severity: rule.severity, thresholdPct: rule.thresholdPct, capacityMva: outcome.capacityMva, capacitySeason: rule.capacitySeason }); runtime[key] = next;
        if (Number.isFinite(outcome.loadingPct) && (!max || outcome.loadingPct > max.loadingPct)) max = { loadingPct: outcome.loadingPct, entity };
        const type = next.changed ? (next.state === 'ACTIVE' ? 'activated' : next.state === 'NORMAL' ? 'cleared' : 'data-unavailable') : next.alertDue ? 'repeated' : ''; let event = null; if (type) { if (type === 'activated') newCount++; if (type === 'cleared') cleared++; event = eventFor(type, rule, entity, prior, next, outcome, key); events = WebSCADAAlarmModel.append(events, event, WebSCADAAlarmModel.LIMITS.events); emittedEvents.push(event); }
        const wantsNotification = next.alertDue && rule.notificationEnabled && globalSettings.alarmNotificationsEnabled && notifications < WebSCADAAlarmModel.LIMITS.notificationBurst; const wantsSound = next.alertDue && rule.soundEnabled && globalSettings.alarmSoundEnabled;
        if (wantsNotification) { try { await WebSCADAAlarmNotifications.alarm(rule, next); next.lastNotifiedAt = Date.now(); notifications++; lastNotificationResult = 'ok'; if (event) event.notificationSent = true; } catch (error) { lastNotificationResult = error.message || String(error); } }
        if (wantsSound) { soundSeverity = rule.severity === 'critical' ? 'critical' : soundSeverity || 'warning'; if (event) soundEvents.push(event); }
        if (next.alertDue) next.lastAlertedAt = Date.now();
        if (Number.isFinite(outcome.loadingPct) && (rule.scopeType === 'selected' || rule.scopeType === 'multi' || next.state === 'ACTIVE')) samples[entity.entityId] = WebSCADAAlarmModel.append(samples[entity.entityId], { at: iso(), entityId: entity.entityId, loadingPct: outcome.loadingPct, activeMw: outcome.activeMw, reactiveMvar: outcome.reactiveMvar, capacityMva: outcome.capacityMva, state: next.state }, WebSCADAAlarmModel.LIMITS.samplesPerEntity);
      }
      if (newCount > WebSCADAAlarmModel.LIMITS.notificationBurst) { try { await WebSCADAAlarmNotifications.summary(newCount); } catch (error) { lastNotificationResult = error.message || String(error); } }
      if (soundSeverity) { try { await WebSCADAAlarmNotifications.sound(soundSeverity); lastSoundResult = soundSeverity; soundEvents.forEach(event => { event.soundPlayed = true; }); } catch (error) { lastSoundResult = error.message || String(error); } }
      const active = activeCount(runtime); WebSCADAAlarmNotifications.activeBadge(active); const checks = { ...reconciled.checks }; prepared.forEach(rule => { checks[rule.id] = Date.now(); }); const cycle = { id: `${started}`, source: trigger, startedAt: new Date(started).toISOString(), completedAt: iso(), durationMs: Date.now() - started, ruleCount: prepared.length, dueRuleCount: prepared.length, monitoredEntityCount: queryPlan.entities.length, measurementIdCount: queryPlan.measurementIds.length, snapshotReuseCount: snapshot.reusedIds.length, networkMissingIdCount: snapshot.missingIds.length, returnedRowCount: values.length, matchedEntityCount: queryPlan.entities.length, missingEntityCount: 0, activeAlarmCount: active, newAlarmCount: newCount, clearedAlarmCount: cleared, maxLoadingPct: max?.loadingPct || null, maxLoadingEntityId: max?.entity?.entityId || '', maxLoadingEntityName: max?.entity?.entityDisplayName || max?.entity?.entityName || '', authMode: result?.authMode || 'snapshot', querySource: source, error: '' };
      const status = await finalizeCycleStatus(startStatus, started, trigger, { enabled: true, activeAlarmCount: active, ruleCount: cycle.ruleCount, dueRuleCount: cycle.dueRuleCount, monitoredEntityCount: cycle.monitoredEntityCount, measurementIdCount: cycle.measurementIdCount, snapshotReuseCount: cycle.snapshotReuseCount, networkMissingIdCount: cycle.networkMissingIdCount, lastAuthMode: cycle.authMode, lastNotificationResult, lastSoundResult, notificationPermission: saved[KEYS.notificationStatus]?.notificationPermission || 'unknown', schedulerDelayMs: 0, gapDetected: saved[KEYS.status]?.lastCompletedAt && Date.now() - new Date(saved[KEYS.status].lastCompletedAt).getTime() > 150000 }); await set({ [KEYS.runtime]: runtime, [KEYS.checks]: checks, [KEYS.events]: events, [KEYS.samples]: samples, [KEYS.cycles]: WebSCADAAlarmModel.append(saved[KEYS.cycles], cycle, WebSCADAAlarmModel.LIMITS.cycles), [KEYS.status]: status }); await broadcast(emittedEvents); return { ok: true, cycle };
    } catch (error) { const prior = await get(KEYS.status, KEYS.cycles); const status = await finalizeCycleStatus(prior[KEYS.status] || {}, started, trigger, { enabled: true, error: error.message || String(error), lastAuthMode: error.authMode || 'none' }); const cycle = { id: `${started}`, source: trigger, startedAt: new Date(started).toISOString(), completedAt: iso(), durationMs: Date.now() - started, error: status.lastError, activeAlarmCount: status.activeAlarmCount || 0 }; await set({ [KEYS.cycles]: WebSCADAAlarmModel.append(prior[KEYS.cycles], cycle, WebSCADAAlarmModel.LIMITS.cycles) }); return { ok: false, error: status.lastError }; }
    finally { await release(); }
  }
  async function syncCatalog(value) { if (!Array.isArray(value)) return false; await set({ [KEYS.catalog]: value, [KEYS.catalogVersion]: chrome.runtime.getManifest().version }); return true; }
  return { KEYS, catalog, plan, snapshotRows, dueRules, reconcileAlarmRuntime, reconcileStored, recordWake, finalizeCycleStatus, run, syncCatalog };
})();
if (typeof module === 'object' && module.exports) module.exports = WebSCADAAlarmMonitor;
