importScripts('../core/ytbs-hierarchy.js', '../core/webscada-settings.js', '../core/alarm-model.js', '../core/alarm-catalog.js', '../core/alarm-exemptions.js', '../core/alarm-evaluator.js', '../core/live-measurement-cache.js', 'request-coordinator.js', 'superset-auth.js', 'superset-api.js', 'query-service.js', 'alarm-notifications.js', 'alarm-monitor.js', 'alarm-scheduler.js', 'map-refresh.js');

chrome.action.onClicked.addListener(() => chrome.tabs.create({ url: chrome.runtime.getURL('app.html') }));

const activeAlarmCount = runtime => Object.values(runtime || {}).filter(entry => entry.state === 'ACTIVE' || entry.state === 'ACTIVE_DATA_UNAVAILABLE').length;
async function migrateLegacyBaraRules() { const keys = WebSCADAAlarmMonitor.KEYS; const data = await chrome.storage.local.get(keys.rules); const migration = WebSCADAAlarmMonitor.migrateLegacyBaraRules(data[keys.rules] || []); if (migration.changed) await WebSCADAAlarmMonitor.commitConfig({ [keys.rules]: migration.rules }); return migration; }
async function alarmState() {
  await migrateLegacyBaraRules();
  const keys = WebSCADAAlarmMonitor.KEYS; let data = await chrome.storage.local.get([keys.settings, keys.rules, keys.runtime, keys.checks, keys.events, keys.cycles, keys.samples, keys.status, keys.notificationStatus, keys.exemptions, keys.revision, WebSCADAMapRefresh.STATUS]); const items = await WebSCADAAlarmMonitor.catalog(); const seeded = await WebSCADAAlarmMonitor.ensureDefaultExemptions(items); if (seeded.changed) data = await chrome.storage.local.get([keys.settings, keys.rules, keys.runtime, keys.checks, keys.events, keys.cycles, keys.samples, keys.status, keys.notificationStatus, keys.exemptions, keys.revision, WebSCADAMapRefresh.STATUS]); const rules = data[keys.rules] || []; const exemptions = WebSCADAAlarmExemptions.normalize(data[keys.exemptions]); const reconciled = WebSCADAAlarmMonitor.reconcileAlarmRuntime(rules, data[keys.runtime], data[keys.checks], items, exemptions); const active = activeAlarmCount(reconciled.runtime); const status = { ...(data[keys.status] || { enabled: false }), activeAlarmCount: active, exemptEntityCount: exemptions.length, configRevision: Number(data[keys.revision] || 0) };
  if (JSON.stringify(reconciled.runtime) !== JSON.stringify(data[keys.runtime] || {}) || JSON.stringify(reconciled.checks) !== JSON.stringify(data[keys.checks] || {}) || Number(data[keys.status]?.activeAlarmCount || 0) !== active) await chrome.storage.local.set({ [keys.runtime]: reconciled.runtime, [keys.checks]: reconciled.checks, [keys.status]: status });
  WebSCADAAlarmNotifications.activeBadge(active);
  return { ok: true, settings: data[keys.settings] || { backgroundMonitoringEnabled: false }, globalSettings: await WebSCADASettings.load(), rules, runtime: reconciled.runtime, events: data[keys.events] || [], cycles: data[keys.cycles] || [], samples: data[keys.samples] || {}, exemptions, status, notification: data[keys.notificationStatus] || {}, mapRefresh: data[WebSCADAMapRefresh.STATUS] || {}, coordinator: WebSCADARequestCoordinator.state() };
}
async function alarmMessage(message) {
  await migrateLegacyBaraRules();
  const keys = WebSCADAAlarmMonitor.KEYS; const payload = message.payload || {};
  if (message.type === 'ALARM_GET_STATE' || message.type === 'ALARM_GET_HISTORY') return alarmState();
  if (message.type === 'ALARM_SET_ENABLED') { const old = await chrome.storage.local.get([keys.settings, keys.rules, keys.runtime, keys.checks, keys.exemptions]); const rules = old[keys.rules] || []; const all = await WebSCADAAlarmMonitor.catalog(); const reconciled = WebSCADAAlarmMonitor.reconcileAlarmRuntime(rules, old[keys.runtime], old[keys.checks], all, old[keys.exemptions]); await WebSCADAAlarmMonitor.commitConfig({ [keys.settings]: { ...(old[keys.settings] || {}), backgroundMonitoringEnabled: Boolean(payload.enabled) }, [keys.runtime]: reconciled.runtime, [keys.checks]: reconciled.checks }); await WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); return alarmState(); }
  if (message.type === 'ALARM_SAVE_RULE') { const all = await WebSCADAAlarmMonitor.catalog(); const normalized = WebSCADAAlarmModel.rule(payload); if (normalized.scopeType === 'filter' && normalized.filters?.type === 'bara') return { ok: false, error: 'Bara yüklenme alarmı desteklenmiyor.' }; if (normalized.scopeType === 'filter') normalized.filters = { ...(normalized.filters || {}), type: normalized.filters?.type === 'trafo' ? 'trafo' : 'hat' }; const old = await chrome.storage.local.get([keys.rules, keys.runtime, keys.checks, keys.exemptions]); const entities = WebSCADAAlarmMonitor.resolveRule(normalized, all, old[keys.exemptions]).filter(x => x.winterCapacityMva || x.summerCapacityMva).filter(x => x.activeDescriptors.length || x.reactiveDescriptors.length); const error = WebSCADAAlarmModel.validate(normalized, entities.length); if (error) return { ok: false, error }; const rules = old[keys.rules] || []; const index = rules.findIndex(rule => rule.id === normalized.id); if (index >= 0) rules[index] = normalized; else rules.push(normalized); const reconciled = WebSCADAAlarmMonitor.reconcileAlarmRuntime(rules, old[keys.runtime], old[keys.checks], all, old[keys.exemptions]); await WebSCADAAlarmMonitor.commitConfig({ [keys.rules]: rules, [keys.runtime]: reconciled.runtime, [keys.checks]: reconciled.checks }); await WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); WebSCADAAlarmMonitor.run('rule-save', { forceRuleIds: [normalized.id] }).catch(() => {}); return alarmState(); }
  if (message.type === 'ALARM_DELETE_RULE') { const old = await chrome.storage.local.get([keys.rules, keys.runtime, keys.checks, keys.exemptions]); const rules = (old[keys.rules] || []).filter(rule => rule.id !== String(payload.id)); const all = await WebSCADAAlarmMonitor.catalog(); const reconciled = WebSCADAAlarmMonitor.reconcileAlarmRuntime(rules, old[keys.runtime], old[keys.checks], all, old[keys.exemptions]); await WebSCADAAlarmMonitor.commitConfig({ [keys.rules]: rules, [keys.runtime]: reconciled.runtime, [keys.checks]: reconciled.checks }); await WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); return alarmState(); }
  if (message.type === 'ALARM_EXEMPTIONS_GET') { const state = await alarmState(); return { ok: true, exemptions: state.exemptions, catalog: await WebSCADAAlarmMonitor.catalog() }; }
  if (message.type === 'ALARM_EXEMPTIONS_ADD' || message.type === 'ALARM_EXEMPTIONS_REMOVE' || message.type === 'ALARM_EXEMPTIONS_CLEAR') { const old = await chrome.storage.local.get([keys.rules, keys.runtime, keys.checks, keys.exemptions]); const all = await WebSCADAAlarmMonitor.catalog(); let exemptions = WebSCADAAlarmExemptions.normalize(old[keys.exemptions]); if (message.type === 'ALARM_EXEMPTIONS_ADD') { const wanted = new Set((payload.entities || []).map(entity => `${entity.entityType}:${entity.entityId}`)); exemptions = WebSCADAAlarmExemptions.normalize([...exemptions, ...all.filter(entity => wanted.has(`${entity.entityType}:${entity.entityId}`)).map(WebSCADAAlarmExemptions.fromEntity)]); } else if (message.type === 'ALARM_EXEMPTIONS_REMOVE') exemptions = exemptions.filter(entity => !(entity.entityId === String(payload.entityId) && entity.entityType === String(payload.entityType))); else exemptions = []; const rules = old[keys.rules] || []; const reconciled = WebSCADAAlarmMonitor.reconcileAlarmRuntime(rules, old[keys.runtime], old[keys.checks], all, exemptions); await WebSCADAAlarmMonitor.commitConfig({ [keys.exemptions]: exemptions, [keys.exemptionsSeeded]: true, [keys.runtime]: reconciled.runtime, [keys.checks]: reconciled.checks }); return alarmState(); }
  if (message.type === 'ALARM_CLEAR_EVENTS') { await chrome.storage.local.set({ [keys.events]: [] }); return alarmState(); }
  if (message.type === 'ALARM_CLEAR_CYCLES') { await chrome.storage.local.set({ [keys.cycles]: [] }); return alarmState(); }
  if (message.type === 'ALARM_ACK' || message.type === 'ALARM_SNOOZE') { const old = await chrome.storage.local.get(keys.runtime); const runtime = old[keys.runtime] || {}; const entry = runtime[String(payload.key)]; if (!entry) return { ok: false, error: 'Alarm bulunamadi.' }; runtime[String(payload.key)] = message.type === 'ALARM_ACK' ? { ...entry, acknowledgedAt: Date.now() } : WebSCADAAlarmModel.snooze(entry, payload.minutes || 15); await chrome.storage.local.set({ [keys.runtime]: runtime }); return alarmState(); }
  if (message.type === 'ALARM_RUN_NOW') return WebSCADAAlarmMonitor.run('alarm-manual', { forceAll: true, forceFresh: true });
  if (message.type === 'ALARM_TEST_NOTIFICATION') return WebSCADAAlarmNotifications.notify('webscada-alarm:test', { title: 'WebSCADA - Test bildirimi', message: 'Bildirim hatti calisiyor.' });
  if (message.type === 'ALARM_TEST_SOUND') return WebSCADAAlarmNotifications.sound(payload.severity === 'critical' ? 'critical' : 'warning');
  if (message.type === 'ALARM_SYNC_CATALOG') return { ok: await WebSCADAAlarmMonitor.syncCatalog(payload.catalog) };
  if (message.type === 'ALARM_RECORD_REFRESH_SUMMARY') { const old = await chrome.storage.local.get(keys.cycles); const entry = { id: `${Date.now()}`, source: payload.source || 'map-manual', startedAt: payload.startedAt || new Date().toISOString(), completedAt: payload.completedAt || new Date().toISOString(), durationMs: Number(payload.durationMs || 0), ruleCount: 0, monitoredEntityCount: Number(payload.entityCount || 0), measurementIdCount: Number(payload.measurementIdCount || 0), returnedRowCount: Number(payload.returnedRowCount || 0), activeAlarmCount: 0, error: payload.error || '' }; await chrome.storage.local.set({ [keys.cycles]: WebSCADAAlarmModel.append(old[keys.cycles], entry, WebSCADAAlarmModel.LIMITS.cycles) }); return { ok: true }; }
  return null;
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (String(message?.type || '').startsWith('ALARM_')) { alarmMessage(message).then(sendResponse).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  const handlers = { SCADA_FETCH: WebSCADAQuery.executeLiveScada, SCADA_HISTORY_FETCH: WebSCADAQuery.executeHistorySeries, SCADA_HISTORICAL_SNAPSHOT_FETCH: WebSCADAQuery.executeHistoricalSnapshot, WEBSCADA_QUERY: WebSCADAQuery.executeWorkspaceQuery };
  if (handlers[message?.type]) { const payload = message.payload || {}; const type = message.type; const key = WebSCADARequestCoordinator.requestKey(type, payload); const priority = WebSCADARequestCoordinator.priorityFor(type, payload); WebSCADARequestCoordinator.run({ key, priority, coalesceKey: type === 'SCADA_FETCH' && priority === 4 ? 'map-auto-refresh' : '', label: type === 'SCADA_FETCH' ? (priority === 4 ? 'Harita otomatik yenileme' : 'Harita yenileme') : type === 'WEBSCADA_QUERY' ? 'Manuel sorgu' : 'Gecmis sorgu' }, () => handlers[type](payload)).then(sendResponse).catch(error => sendResponse({ ok: false, error: error.message || String(error), errorType: 'BACKGROUND_ERROR', authMode: 'none', usedFallback: false })); return true; }
  if (message?.type === 'WEBSCADA_SETTINGS_GET') { WebSCADASettings.load().then(settings => sendResponse({ ok: true, settings })).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  if (message?.type === 'WEBSCADA_SETTINGS_SAVE') { WebSCADASettings.save(message.payload || {}).then(async settings => { await WebSCADAMapRefresh.ensure(); sendResponse({ ok: true, settings }); }).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  if (message?.type === 'MAP_REFRESH_CONTEXT') { WebSCADAMapRefresh.setContext(message.payload || {}).then(context => sendResponse({ ok: true, context })).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  if (message?.type === 'MAP_REFRESH_RUN_NOW') { WebSCADAMapRefresh.run('map-manual').then(sendResponse).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  if (message?.type === 'WEBSCADA_STATUS') { WebSCADAAuth.loadConfig().then(async config => sendResponse({ ok: true, session: await WebSCADAAuth.ensureSession(config), baseUrl: config.baseUrl })).catch(error => sendResponse({ ok: false, error: error.message || String(error) })); return true; }
  return false;
});

chrome.notifications.onClicked.addListener(notificationId => { if (!notificationId.startsWith('webscada-alarm:')) return; chrome.storage.local.set({ webscadaAlarmUiFocus: { tab: 'alarms', notificationId } }); chrome.tabs.create({ url: chrome.runtime.getURL('app.html') }); });
chrome.notifications.onButtonClicked.addListener((notificationId, buttonIndex) => { const key = buttonIndex === 0 ? WebSCADAAlarmNotifications.alarmKeyFromNotificationId(notificationId) : ''; if (!key) return; alarmMessage({ type: 'ALARM_SNOOZE', payload: { key, minutes: 15 } }).then(result => { if (result?.ok) chrome.notifications.clear(notificationId); }).catch(() => {}); });
chrome.runtime.onInstalled.addListener(() => { WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); WebSCADAMapRefresh.ensure(); });
chrome.runtime.onStartup.addListener(() => { WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); WebSCADAMapRefresh.ensure(); });
migrateLegacyBaraRules().catch(() => {}); WebSCADAAlarmScheduler.ensureBackgroundMonitorAlarm(); WebSCADAMapRefresh.ensure();
